name: flutter_thailand_provinces
description: The package for creating a database of provinces, districts and sub-districts of Thailand with basic information such as Thai names, English names and postal numbers. For use in a Flutter.
version: 1.0.1
author: benznest <benz7net@gmail.com>
homepage: https://github.com/benznest/flutter_thailand_provinces

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/thailand.db